---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cyclescape]
      - recipe[munin]
    attributes:
    data_bags_path: test/integration/databags
